server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      local: common, domain, auth, infra

google:
  rtdn:
    email: ${GOOGLE_RTDN_EMAIL}
    audience: ${GOOGLE_RTDN_AUDIENCE}
    jwks-uri: ${GOOGLE_RTDN_JWKS_URI}